server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
#            allowCredentials: true

      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-AUTH-SERVICE
          uri: lb://USER-MANAGEMENT-SERVICE
#          uri: http://localhost:8110
          predicates:
            - Path=/api/auths/**

        - id: USER-IMAGE-SERVICE
          uri: lb://USER-MANAGEMENT-SERVICE
#          uri: http://localhost:8110
          predicates:
          - Path=/api/images/**

        - id: STUDENT-MANAGEMENT-SERVICE
          uri: lb://STUDENT-MANAGEMENT-SERVICE
#          uri: http://localhost:8110
          predicates:
            - Path=/api/students/**
          filters:
            - AuthFilter

        - id: ROOM-MANAGEMENT-SERVICE
          uri: lb://NOTIFICATION-MANAGEMENT-SERVICE
#          uri: http://localhost:8081
          predicates:
            - Path=/api/rooms/**
          filters:
            - AuthFilter


        - id: USER-MANAGEMENT-SERVICE
          uri: lb://USER-MANAGEMENT-SERVICE
#          uri: http://localhost:8110
          predicates:
            - Path=/api/users/**
          filters:
            - AuthFilter

        - id: EMAIL-NOTIFICATION-SERVICE
          uri: lb://EMAIL-NOTIFICATION-SERVICE
#          uri: http://localhost:8082
          predicates:
              - Path=/api/notifications/**
          filters:
              - AuthFilter

        - id: STUDENT-GRADE-SERVICE
          uri: lb://STUDENT-GRADE-SERVICE
#          uri: http://localhost:8083
          predicates:
            - Path=/api/grades/**
          filters:
            - AuthFilter

        - id: STUDENT-REGISTRATION-SERVICE
          uri: lb://STUDENT-REGISTRATION-SERVICE
          predicates:
            - Path=/api/registrations/**
          filters:
            - AuthFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

